/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.LoadMoneyController;
import javax.swing.*;

/**
 *
 * @author r4hul
 */
public class LoadMoney extends javax.swing.JFrame {
  

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoadMoney.class.getName());
    private String userEmail;
    public Dashboard dashboardRef;
    

    /**
     * Creates new form LoadMoney
     */
    public LoadMoney(String email, Dashboard dashboardRef) {
        initComponents(); 
        this.userEmail = email;
        this.dashboardRef = dashboardRef;
        
        new LoadMoneyController(this, userEmail);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        amnt_value2 = new javax.swing.JLabel();
        value = new javax.swing.JTextField();
        Password_value = new javax.swing.JPasswordField();
        Password = new javax.swing.JLabel();
        amnt_text = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        Button.setText("Submit");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(Button);
        Button.setBounds(270, 420, 130, 24);

        amnt_value2.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 24)); // NOI18N
        amnt_value2.setForeground(new java.awt.Color(255, 255, 255));
        amnt_value2.setText("Load Money");
        jPanel2.add(amnt_value2);
        amnt_value2.setBounds(610, 181, 180, 20);

        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });
        jPanel2.add(value);
        value.setBounds(320, 260, 160, 40);
        jPanel2.add(Password_value);
        Password_value.setBounds(330, 340, 150, 40);

        Password.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 24)); // NOI18N
        Password.setText("Password");
        jPanel2.add(Password);
        Password.setBounds(200, 340, 120, 31);

        amnt_text.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 24)); // NOI18N
        amnt_text.setText("Amount");
        jPanel2.add(amnt_text);
        amnt_text.setBounds(190, 260, 100, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-270, 0, 1830, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1325, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed


    }//GEN-LAST:event_ButtonActionPerformed
    public JButton getButton() {
        return Button;
    }

    public JTextField getValue() {
        return value;
    }

    public JPasswordField getPasswordValue() {
        return Password_value;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField Password_value;
    private javax.swing.JLabel amnt_text;
    private javax.swing.JLabel amnt_value2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
