/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.CurrencyConverterController;



/**
 *
 * @author utpre
 */
public class CurrencyConverterUI extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyConverterUI
     */
    public CurrencyConverterUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        converterPanel = new javax.swing.JPanel();
        innerPanel = new javax.swing.JPanel();
        fromComboBox = new javax.swing.JComboBox<>();
        toComboBox = new javax.swing.JComboBox<>();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        currencyconverterLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        converterPanel.setBackground(new java.awt.Color(151, 198, 237));

        innerPanel.setBackground(new java.awt.Color(255, 255, 255));

        fromComboBox.setBackground(new java.awt.Color(204, 204, 204));
        fromComboBox.setFont(new java.awt.Font("Dubai Light", 1, 16)); // NOI18N
        fromComboBox.setForeground(new java.awt.Color(0, 0, 102));
        fromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NPR", "USD", "EUR", "GBP", "AUD", "JPY", "THB", "CNY", "CAD", " ", " " }));
        fromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromComboBoxActionPerformed(evt);
            }
        });

        toComboBox.setBackground(new java.awt.Color(204, 204, 204));
        toComboBox.setFont(new java.awt.Font("Dubai Light", 1, 16)); // NOI18N
        toComboBox.setForeground(new java.awt.Color(0, 0, 102));
        toComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "NPR", "EUR", "GBP", "AUD", "JPY", "THB", "CNY", "CAD", " ", " " }));
        toComboBox.setToolTipText("");

        fromLabel.setFont(new java.awt.Font("Dubai Light", 1, 16)); // NOI18N
        fromLabel.setForeground(new java.awt.Color(0, 0, 102));
        fromLabel.setText("FROM:");

        toLabel.setFont(new java.awt.Font("Dubai Light", 1, 16)); // NOI18N
        toLabel.setForeground(new java.awt.Color(0, 0, 102));
        toLabel.setText("TO:");

        convertButton.setBackground(new java.awt.Color(0, 0, 102));
        convertButton.setFont(new java.awt.Font("Dubai Light", 1, 16)); // NOI18N
        convertButton.setForeground(new java.awt.Color(255, 255, 255));
        convertButton.setText("CONVERT");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Dubai Light", 1, 16)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(0, 0, 102));
        resultLabel.setText("RESULT:");

        amountTextField.setBackground(new java.awt.Color(0, 0, 102));
        amountTextField.setFont(new java.awt.Font("Dubai Light", 1, 16)); // NOI18N
        amountTextField.setForeground(new java.awt.Color(255, 255, 255));
        amountTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountTextField.setAlignmentX(1.0F);
        amountTextField.setAlignmentY(1.0F);
        amountTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });

        amountLabel.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(0, 0, 102));
        amountLabel.setText("AMOUNT:");

        javax.swing.GroupLayout innerPanelLayout = new javax.swing.GroupLayout(innerPanel);
        innerPanel.setLayout(innerPanelLayout);
        innerPanelLayout.setHorizontalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLayout.createSequentialGroup()
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(innerPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(innerPanelLayout.createSequentialGroup()
                                .addComponent(toLabel)
                                .addGap(74, 74, 74)
                                .addComponent(toComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(innerPanelLayout.createSequentialGroup()
                                .addComponent(fromLabel)
                                .addGap(54, 54, 54)
                                .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultLabel)))
                    .addGroup(innerPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(innerPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(amountLabel)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        innerPanelLayout.setVerticalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromLabel))
                .addGap(18, 18, 18)
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel))
                .addGap(26, 26, 26)
                .addComponent(convertButton)
                .addGap(18, 18, 18)
                .addComponent(resultLabel)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 102));
        backButton.setText("BACK");
        backButton.setMaximumSize(new java.awt.Dimension(283, 232));
        backButton.setMinimumSize(new java.awt.Dimension(283, 232));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        currencyconverterLabel.setBackground(new java.awt.Color(255, 255, 255));
        currencyconverterLabel.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        currencyconverterLabel.setForeground(new java.awt.Color(0, 0, 102));
        currencyconverterLabel.setText("      CURRENCY CONVERTER");
        currencyconverterLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));
        currencyconverterLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout converterPanelLayout = new javax.swing.GroupLayout(converterPanel);
        converterPanel.setLayout(converterPanelLayout);
        converterPanelLayout.setHorizontalGroup(
            converterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(converterPanelLayout.createSequentialGroup()
                .addGroup(converterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(converterPanelLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addGroup(converterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(innerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currencyconverterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        converterPanelLayout.setVerticalGroup(
            converterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(converterPanelLayout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(currencyconverterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(innerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(converterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(converterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFieldActionPerformed

    private void fromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromComboBoxActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:
        try {
            double amount = Double.parseDouble(amountTextField.getText());  // Get entered amount
            String fromCurrency = fromComboBox.getSelectedItem().toString();  // Get 'From' currency
            String toCurrency = toComboBox.getSelectedItem().toString();  // Get 'To' currency

            double convertedAmount = CurrencyConverterController.convert(amount, fromCurrency, toCurrency); // Perform conversion
            
            resultLabel.setText(String.format("%.0f %s = %.3f %s", amount, fromCurrency, convertedAmount, toCurrency));


            
        } catch (NumberFormatException ex) {
            resultLabel.setText("Please enter a valid number.");
        }

    }//GEN-LAST:event_convertButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close currency converter screen
        
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverterUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton convertButton;
    private javax.swing.JPanel converterPanel;
    private javax.swing.JLabel currencyconverterLabel;
    private javax.swing.JComboBox<String> fromComboBox;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JComboBox<String> toComboBox;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
