/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.*;
import Database.*;
import Model.Session;
import controller.DashboardController;
import controller.NotificationController;
import controller.TransactionHistoryController;
import controller.profileController;
import javax.swing.*;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.logging.Logger;

/**
 *
 * @author r4hul
 */
public class Dashboard extends javax.swing.JFrame {
  
    private static final Logger logger = Logger.getLogger(Dashboard.class.getName());
    private DashboardController controller;
    private final String email;
   private boolean isBalanceVisible = true;
    private String originalBalance;
    

    /**
     * Creates new form NewJFrame
     * @param emailText
     */
    public Dashboard(String email) {
        initComponents();
        this.email = email;
        controller = new DashboardController(email, this);
        controller.loadUserBalance();
        event.setActionCommand("event");
        event1.setActionCommand("event1");
        controller.initializeEventButtons();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Right_bar = new javax.swing.JPanel();
        accBalance3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        event = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        event1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sendMoney = new javax.swing.JButton();
        CurrencyConvert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Bookingopenbtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Balance = new javax.swing.JLabel();
        Coin_Image = new javax.swing.JLabel();
        accBalance = new javax.swing.JLabel();
        Gdmrng = new javax.swing.JLabel();
        Filter = new javax.swing.JComboBox<>();
        accBalance1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        accBalance2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        load_money = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        profilebtn = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        loadMoneyButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        Noti = new javax.swing.JButton();
        btnRefreshHistory = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Right_bar.setBackground(new java.awt.Color(212, 235, 253));

        accBalance3.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 24)); // NOI18N
        accBalance3.setText("Events");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        event.setText("Book Now");
        event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel3.setText("Venue: Patan Durbar Square, Lalitpur");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel4.setText("Time: 5:00 PM - 9:00 PM");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel5.setText("Artist: Traditional Newa Band \"Nepal Bhasa\"");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Arcade-Zone-Business-Interactive-Fun-Hub.pptx (3).png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel10.setText("Price: 1500");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(event)
                        .addGap(22, 22, 22))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(event)
                            .addComponent(jLabel10))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        event1.setText("Book Now");
        event1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Arcade-Zone-Business-Interactive-Fun-Hub.pptx (4).png"))); // NOI18N

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel7.setText("Venue:  Bhaktapur Durbar Square, Bhaktapur");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel8.setText("Time: 10:00 PM - 1:00 AM");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel9.setText("Artist: Folk Dance Group \"Mandala Cultural Troupe\"");

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel11.setText("Price: 3000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(27, 27, 27)
                        .addComponent(event1)
                        .addGap(20, 20, 20))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(event1)
                            .addComponent(jLabel11))))
                .addContainerGap())
        );

        sendMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SendMoney.png"))); // NOI18N
        sendMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMoneyActionPerformed(evt);
            }
        });

        CurrencyConvert.setText("esrfvyeu");
        CurrencyConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyConvertActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("SendMoney");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("CurrencyConverter");

        Bookingopenbtn.setText("jButton1");
        Bookingopenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingopenbtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Ticket Booking");

        javax.swing.GroupLayout Right_barLayout = new javax.swing.GroupLayout(Right_bar);
        Right_bar.setLayout(Right_barLayout);
        Right_barLayout.setHorizontalGroup(
            Right_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_barLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(Right_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Right_barLayout.createSequentialGroup()
                        .addGroup(Right_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accBalance3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Right_barLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))
                            .addComponent(sendMoney, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(Right_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Right_barLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel12))
                            .addGroup(Right_barLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(CurrencyConvert)))
                        .addGroup(Right_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Right_barLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Bookingopenbtn))
                            .addGroup(Right_barLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        Right_barLayout.setVerticalGroup(
            Right_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_barLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(Right_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CurrencyConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sendMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bookingopenbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Right_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(216, 216, 216)
                .addComponent(accBalance3)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hide_3507619.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(290, 160, 30, 27);

        Balance.setFont(new java.awt.Font("Jost", 1, 18)); // NOI18N
        Balance.setForeground(new java.awt.Color(255, 255, 255));
        Balance.setText("Rs 12,760.90");
        jPanel3.add(Balance);
        Balance.setBounds(150, 180, 230, 50);

        Coin_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Coin_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Coin Image.png"))); // NOI18N
        jPanel3.add(Coin_Image);
        Coin_Image.setBounds(140, 130, 355, 180);

        accBalance.setFont(new java.awt.Font("AvantGarde LT Medium", 0, 18)); // NOI18N
        accBalance.setText("Transaction");
        jPanel3.add(accBalance);
        accBalance.setBounds(140, 350, 100, 20);

        Gdmrng.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 24)); // NOI18N
        Gdmrng.setText("Good Morning");
        jPanel3.add(Gdmrng);
        Gdmrng.setBounds(137, 14, 168, 32);

        Filter.setBackground(new java.awt.Color(151, 198, 237));
        Filter.setForeground(new java.awt.Color(255, 255, 255));
        Filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit", "Debit", "All" }));
        Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterActionPerformed(evt);
            }
        });
        jPanel3.add(Filter);
        Filter.setBounds(230, 390, 76, 22);

        accBalance1.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 14)); // NOI18N
        accBalance1.setText("Filter By");
        jPanel3.add(accBalance1);
        accBalance1.setBounds(150, 390, 60, 19);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(150, 320, 720, 3);

        accBalance2.setFont(new java.awt.Font("AvantGarde LT Medium", 1, 14)); // NOI18N
        accBalance2.setText("Account Balance");
        jPanel3.add(accBalance2);
        accBalance2.setBounds(137, 106, 117, 19);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        transactionTable.setFont(new java.awt.Font("Nimbus Sans", 1, 12)); // NOI18N
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Date", "Details", "Amount", "Balance"
            }
        ));
        jScrollPane1.setViewportView(transactionTable);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(140, 430, 740, 220);

        load_money.setText("jLabel2");
        jPanel3.add(load_money);
        load_money.setBounds(190, 250, 40, 50);

        jPanel1.setBackground(new java.awt.Color(212, 235, 253));

        profilebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pfp.png"))); // NOI18N
        profilebtn.setText("jButton2");
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Logout)
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(profilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(profilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 537, Short.MAX_VALUE)
                .addComponent(Logout)
                .addGap(52, 52, 52))
        );

        jPanel3.add(jPanel1);
        jPanel1.setBounds(0, 0, 110, 700);

        loadMoneyButton.setBackground(new java.awt.Color(0, 153, 255));
        loadMoneyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Plus.png"))); // NOI18N
        loadMoneyButton.setText("jButton1");
        loadMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMoneyButtonActionPerformed(evt);
            }
        });
        jPanel3.add(loadMoneyButton);
        loadMoneyButton.setBounds(200, 270, 30, 20);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(100, 10, 0, 3);

        Noti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/notifications.png"))); // NOI18N
        Noti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotiActionPerformed(evt);
            }
        });
        jPanel3.add(Noti);
        Noti.setBounds(900, 10, 50, 50);

        btnRefreshHistory.setText("Refresh");
        btnRefreshHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshHistoryActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefreshHistory);
        btnRefreshHistory.setBounds(330, 390, 72, 23);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(Right_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Right_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
   
    private void eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventActionPerformed
        // TODO add your handling code here:
         controller.handleEventBooking("event", 1500.0, event);
    }//GEN-LAST:event_eventActionPerformed

    private void loadMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMoneyButtonActionPerformed
        // TODO add your handling code here:
        controller.openLoadMoneyWindow();
    }//GEN-LAST:event_loadMoneyButtonActionPerformed

    private void FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilterActionPerformed

    private void event1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event1ActionPerformed
        // TODO add your handling code here:
         controller.handleEventBooking("event1", 3000.0, event1);
    }//GEN-LAST:event_event1ActionPerformed

    private void sendMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendMoneyActionPerformed

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed
       
        // TODaO add your handling co
    }//GEN-LAST:event_profilebtnActionPerformed

    private void NotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotiActionPerformed
        // TODO add your handling code here:
        new NotificationUI().setVisible(true);
    }//GEN-LAST:event_NotiActionPerformed

    private void CurrencyConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyConvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrencyConvertActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void btnRefreshHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshHistoryActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnRefreshHistoryActionPerformed

    private void BookingopenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingopenbtnActionPerformed
        // TODO add your handling code here:
        OnlineBooking ob = new OnlineBooking();
       ob.setVisible(true);
    }//GEN-LAST:event_BookingopenbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        togglebalance();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void refreshBalance() {
        controller.refreshBalance();

    }
       public void addTransferListener(ActionListener listener) {
        sendMoney.addActionListener(listener);
    }
       
    public JLabel getBalanceLabel() {
    return this.Balance;
}
    public JButton[] getEventButtons() {
    return new JButton[]{event, event1};
}


    public JButton getProfileButton() {
    return profilebtn;
}
    
      public DashboardController getDashboardController() {
        return controller;
    }
   
      public JButton getCurrencyConvert() {
    return CurrencyConvert;
}
      
      public JButton getLogoutBtn() {
    return Logout;
}
      
      public JButton getRefreshHistoryButton() {
    return btnRefreshHistory;
}

public JTable getTransactionTable() {
    return transactionTable;
}

public JComboBox<String> getFilterComboBox() {
    return Filter;
}






    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balance;
    private javax.swing.JButton Bookingopenbtn;
    private javax.swing.JLabel Coin_Image;
    private javax.swing.JButton CurrencyConvert;
    private javax.swing.JComboBox<String> Filter;
    private javax.swing.JLabel Gdmrng;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Noti;
    private javax.swing.JPanel Right_bar;
    private javax.swing.JLabel accBalance;
    private javax.swing.JLabel accBalance1;
    private javax.swing.JLabel accBalance2;
    private javax.swing.JLabel accBalance3;
    private javax.swing.JButton btnRefreshHistory;
    private javax.swing.JButton event;
    private javax.swing.JButton event1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton loadMoneyButton;
    private javax.swing.JLabel load_money;
    private javax.swing.JButton profilebtn;
    private javax.swing.JButton sendMoney;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables

     private void togglebalance() {
    if (isBalanceVisible) {
        
        originalBalance = Balance.getText();
        
        Balance.setText("Rs ********");
        isBalanceVisible = false;
    } else {
        Balance.setText(originalBalance);
        isBalanceVisible = true;
    }
}
public DashboardController getController() {
    return this.controller;
}
   
}
